# Generated by Django 2.0.5 on 2018-05-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messaggio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contatto', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('oggetto', models.CharField(max_length=100)),
                ('contenuto', models.TextField()),
            ],
            options={
                'verbose_name': 'Messaggio',
                'verbose_name_plural': 'Messaggi',
            },
        ),
    ]
